apiVersion: v1
kind: Service
metadata:
  name: virtual-stock-frontend-service
  labels:
    app: virtual-stock-frontend
spec:
  type: NodePort
  selector:
    app: virtual-stock-frontend
  ports:
    - port: 80          # service port
      targetPort: 80    # container port
      nodePort: 30080   # you will access via localhost:30080
